[project]
name = "nicegui-template"
version = "0.1.0"
requires-python = ">= 3.12.4"
dependencies = [
  "nicegui",
  "arq",
  "redis-om",
  "pydantic-settings",
]

[tool.ruff.format]
quote-style = "single"
