version: "3.5"

volumes:
  redis_data:

networks:
  nicegui_network:
    external: true

services:
  redis:
    image: 'docker.io/redis/redis-stack:7.4.0-v3'
    networks:
      - nicegui_network
    volumes:
      - redis_data:/data
      - ./services/redis.conf:/redis.conf

  nicegui:
    image: nicegui_template
    networks:
      - nicegui_network
    environment:
      - REDIS_OM_URL=redis://@redis:6379
    ports:
      - target: 8080
        published: 8080
        mode: host
    volumes: 
      - ./src:/app/src # copy entire app into container
    depends_on:
      - redis
  
  worker:
    image: nicegui_template
    command: arq src.worker.WorkerSettings --watch /app/src
    networks:
      - nicegui_network
    environment:
      - REDIS_OM_URL=redis://@redis:6379
    volumes: 
      - ./src:/app/src # copy entire app into container
    depends_on:
      - redis
  