version: "3.5"

networks:
  nicegui_network:
    external: true

services:
  caddy:
    image: caddy:2.6.4
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - nicegui_network
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
    command: "caddy run --config /etc/caddy/Caddyfile --watch"
